apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  connection-string: "Server=app-mysql;Port=3306;Database=trello_db;User=root;Password=rootpassword;"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trello-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trello-api
  template:
    metadata:
      labels:
        app: trello-api
    spec:
      containers:
        - name: trello-api
          image: <ACR_NAME>.azurecr.io/trello-api:latest
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: connection-string
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: trello-api
spec:
  selector:
    app: trello-api
  ports:
    - port: 5000
      targetPort: 8080
